%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
output_path: "/home/zmi/output"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 752
image_height: 480

# GPU acceleration
use_gpu         : 0
use_gpu_acc_flow: 0
use_gpu_ceres   : 0
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.99995572 , 0.0065681 , -0.00673976 , 0.13614057,
          -0.00651268 , -0.99994507 , -0.00821281 , 0.00209987,
          -0.00679333 , -0.00816855 , 0.99994356 , -0.00578072,
           0.     ,     0.    ,      0.    ,      1.        ]


body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.99999725 , -0.00233389  , -0.0002253 , -0.01417437,
          0.00233356 , -0.99999623 , 0.00144724 , 0.00294746,
         -0.00022867 , 0.00144671 , 0.99999893 , -0.00745275,
          0.    ,      0.    ,      0.    ,      1.        ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 600            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.08  # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# acc_n: 0.1          # accelerometer measurement noise standard deviation. 
# gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
# acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
# gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
# g_norm: 9.81007     # gravity magnitude
# acc_w: 0.00008        # 零偏置随机游走噪声标准差
acc_n: 0.306279     #0.018      # accelerometer measurement noise standard deviation. 
gyr_n: 0.031004   #0.0028      # gyroscope measurement noise standard deviation.     
acc_w: 0.000381  #0.00016      # accelerometer bias random work noise standard deviation.  
gyr_w: 1.422e-05  #2.0e-05     # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007 
#unsynchronization parameters
estimate_td: 1                     # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/zmi/output/pose_graph" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
